{
 "title": "Tatooine Weather",
 "description": "Tatooine Embassy Weather",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "weatherStation", "label": "Station", "query": "show measurements" },
   { "name": "lightningSensor", "label": "Lightning Sensor", "query": "Acurite-6045M" }
  ]
 },
 "panels": [
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"temperature_C\")  *1.8+32 FROM \"${weatherStation}\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rainfall",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EcoWitt-WH40",
     "query": "SELECT cumulative_sum(difference(last(\"rain_mm\")))*0.03937 FROM \"${weatherStation}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "rain_mm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Acurite-5n1",
     "query": "SELECT \"wind_dir_deg\" FROM \"${weatherStation}\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "wind_dir_deg" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dewpoint",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Dewpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"temperature_C\") - ((100-last(\"humidity\")) /5) ) *1.8+32 FROM \"Acurite-5n1\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Windspeed, MPH",
     "measurement": "Acurite-5n1",
     "query": "SELECT \"wind_avg_km_h\" *0.6213712FROM \"${weatherStation}\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "wind_avg_km_h" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Strikes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "query": "SELECT cumulative_sum(difference(last(\"strike_count\"))) FROM \"${lightningSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "strike_count" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Miles" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Acurite-6045M",
     "query": "SELECT \"storm_dist\" * 0.6213712 FROM \"${lightningSensor}\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "storm_dist" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "TEMPS/HUMIDITY",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "humidity", "label": "Temp" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LaCrosse-TX141THBv2",
     "query": "SELECT last(\"temperature_C\")  *1.8+32 FROM \"${weatherStation}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature_C" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *1.8+32" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LaCrosse-TX141THBv2",
     "query": "SELECT (last(\"temperature_C\") - ((100 - last(\"humidity\"))/5)) *1.8+32   FROM \"LaCrosse-TX141THBv2\"\n",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Dewpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"temperature_C\") - ((100-mean(\"humidity\")) /5) ) *1.8+32 FROM \"LaCrosse-TX141THBv2\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rainfall",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "in" }
   ],
   "targets": [
    {
     "alias": "Rainfall in Inches",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(difference(last(\"rain_mm\")))*0.03937 FROM \"${weatherStation}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "mph" }
   ],
   "targets": [
    {
     "alias": "mph",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "${weatherStation}",
     "query": "SELECT last(\"wind_avg_km_h\") * 0.6213712 FROM \"${weatherStation}\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "wind_avg_km_h" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 0.6213712" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lightning",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "miles" }
   ],
   "targets": [
    {
     "alias": "Lightning Strikes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(last(\"strike_count\")) FROM \"${lightningSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Lightning Distance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "query": "SELECT last(\"storm_dist\") * 0.6213712 FROM \"Acurite-6045M\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "storm_dist" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Other weather stations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Acurite 606TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"temperature_C\")  *1.8+32 FROM \"Acurite-606TX\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Hideki TS04",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"temperature_C\")  *1.8+32 FROM \"Hideki-TS04\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Acurite Tower",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"temperature_C\") *1.8+32 FROM \"Acurite-Tower\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Acurite 6045M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "query": "SELECT mean(\"temperature_C\") *1.8+32 FROM \"Acurite-6045M\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature_C" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Acurite 5-in-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Acurite-5n1",
     "query": "SELECT last(\"temperature_C\") *1.8+32 FROM \"Acurite-5n1\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature_C" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LaCrosse Battery Check",
   "type": "graph",
   "description": "Battery Check of Temp Sensor",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LaCrosse-TX141THBv2",
     "select": [
      [
       { "params": [ "battery_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acurite 6045M Battery Check",
   "type": "graph",
   "description": "Battery Check of Lightning Sensor",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 38 },
   "targets": [
    {
     "alias": "ACuRite 06045 Battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "select": [
      [
       { "params": [ "battery_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acurite 6045M Exception Check",
   "type": "graph",
   "description": "Battery Check of Temp Sensor",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 38 },
   "targets": [
    {
     "alias": "AcuRite 06045 Exception",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acurite 5-in-1 Weatherstation",
   "type": "graph",
   "description": "Battery Check of Weatherstation",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 38 },
   "targets": [
    {
     "alias": "AcuRite 5-in-1 Battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-5n1",
     "select": [
      [
       { "params": [ "battery_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "EcoWitt Data Monitor",
   "type": "graph",
   "description": "This panel is only really for monitoring and has no useful info.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EcoWitt-WH40",
     "select": [
      [
       { "params": [ "protocol" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}