{
 "title": "Tatooine Weather",
 "description": "Tatooine Embassy Weather",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "tempSensor",
    "label": "Temp Sensor",
    "query": "Acurite-5n1,Acurite-6045M,LaCrosse-TX141THBv2,Acurite-Tower,Hideki-TS04"
   },
   { "name": "windSensor", "label": "Wind Sensor", "query": "Acurite-5n1, EcoWitt-WS68" },
   {
    "name": "rainSensor",
    "label": "Rain Sensor",
    "query": "EcoWitt-WH40,Acurite-5n1,Hideki-Rain"
   },
   { "name": "lightningSensor", "label": "Lightning Sensor", "query": "Acurite-6045M" },
   { "name": "baroSensor", "label": "Barometer", "query": "Dracal,SenseHat" }
  ]
 },
 "panels": [
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"temperature_C\")  * 1.8+32 FROM \"${tempSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heat Index",
   "type": "stat",
   "description": "Heat Index",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Heatindex",
     "select": [
      [
       { "params": [ "heatindex" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1.8+32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Windchill",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Windchill",
     "select": [
      [
       { "params": [ "Windchill" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1.8 +32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min/Max temps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$tempSensor$/",
     "query": "SELECT max(\"temperature_C\") * 1.8+32 FROM \"autogen\"./^$tempSensor$/ WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "temperature_C" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* 1.8+32" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$tempSensor$/",
     "query": "SELECT min(\"temperature_C\") * 1.8 +32 FROM \"autogen\"./^$tempSensor$/ WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "temperature_C" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "* 1.8 +32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "query": "SELECT last(\"humidity\") FROM \"${tempSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "strike_count" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dewpoint II",
   "type": "stat",
   "description": "Fixed dewpoint panel, I broke it pretty bad somehow",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Dewpoint",
     "measurement": "Dewpoint",
     "query": "SELECT last(\"dewpoint\") * 1.8000 + 32.00 FROM \"Dewpoint\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       { "params": [ "* 1.8000 + 32.00" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "stat",
   "description": "Barometer, MSLP",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$baroSensor$/",
     "select": [
      [
       { "params": [ "Barometer" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rainfall",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EcoWitt-WH40",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"rain_mm\")))*0.03937 FROM \"${rainSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "rain_mm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Windspeed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"wind_avg_km_h\") * 0.6213712 FROM \"${windSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Direction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": " ",
     "groupBy": [
      { "params": [ "90s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$windSensor$/",
     "query": "SELECT mode(\"wind_dir_deg\") FROM \"autogen\"./^$windSensor$/ WHERE $timeFilter GROUP BY time(90s) fill(none)",
     "select": [
      [
       { "params": [ "wind_dir_deg" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "🗲 Strikes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "🗲" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"strike_count\"))) FROM \"${lightningSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "strike_count" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Radiation",
   "type": "stat",
   "description": "Radiation in µSv/hr",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "radusvh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"CPM\")*0.00668  FROM \"cpm\" WHERE $timeFilter GROUP BY time(1h) fill(none)"
    }
   ]
  },
  {
   "title": "Baro",
   "type": "stat",
   "description": "difference between readings for calculating \"rising\" and \"falling\" without looking at a graph.\n\nOfficial UK met standards are what I used because they were the first I found.",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$baroSensor$/",
     "query": "SELECT last(\"Barometer\") FROM /^$baroSensor$/ WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Barometer" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pm10 μg/m³",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AQ",
     "select": [
      [
       { "params": [ "pm10" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url::tag",
       "operator": "=",
       "value": "https://api.airgradient.com/public/api/v1/locations/65141/measures/current?token=4cef3c7c-0191-46e6-8aa0-0e3a519f1c24"
      }
     ]
    }
   ]
  },
  {
   "title": "pm2.5 μg/m³",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AQ",
     "select": [
      [
       { "params": [ "pm02" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url::tag",
       "operator": "=",
       "value": "https://api.airgradient.com/public/api/v1/locations/65141/measures/current?token=4cef3c7c-0191-46e6-8aa0-0e3a519f1c24"
      }
     ]
    }
   ]
  },
  {
   "title": "pm1 μg/m³",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AQ",
     "select": [
      [
       { "params": [ "pm01" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url::tag",
       "operator": "=",
       "value": "https://api.airgradient.com/public/api/v1/locations/65141/measures/current?token=4cef3c7c-0191-46e6-8aa0-0e3a519f1c24"
      }
     ]
    }
   ]
  },
  {
   "title": "pm0.3 μg/m³",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AQ",
     "select": [
      [
       { "params": [ "pm003Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url::tag",
       "operator": "=",
       "value": "https://api.airgradient.com/public/api/v1/locations/65141/measures/current?token=4cef3c7c-0191-46e6-8aa0-0e3a519f1c24"
      }
     ]
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EcoWitt-WS68",
     "select": [
      [
       { "params": [ "uvi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daylight ",
   "type": "stat",
   "description": "Daylight value (in lux)",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EcoWitt-WS68",
     "select": [
      [
       { "params": [ "light_lux" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "TEMPS/HUMIDITY",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LaCrosse-TX141THBv2",
     "query": "SELECT mean(\"temperature_C\")  *1.8+32 FROM \"${tempSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature_C" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *1.8+32" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LaCrosse-TX141THBv2",
     "query": "SELECT mean(\"humidity\") FROM \"${tempSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Dewpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Dewpoint",
     "query": "SELECT mean(\"dewpoint\")  *1.8+32 FROM \"Dewpoint\"  WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Heat Index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Heatindex",
     "query": "SELECT mean(\"heatindex\") *1.8+32 FROM \"Heatindex\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "heatindex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1.8+32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Wind avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "${weatherStation}",
     "query": "SELECT mean(\"wind_avg_km_h\") * 0.6213712 FROM \"${windSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "wind_avg_km_h" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 0.6213712" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "wind gust",
     "query": "SELECT mean(\"wind_max_km_h\") * 0.6213712 FROM \"${windSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "timeseries",
   "description": "Barometric Pressure, normalized for sealevel",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "targets": [
    {
     "alias": "inHg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$baroSensor$/",
     "query": "SELECT mean(\"Barometer\") FROM /^$baroSensor$/ WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "Barometer" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Degrees",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$windSensor$/",
     "query": "SELECT mean(\"wind_dir_deg\") FROM /^$windSensor$/ WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "wind_dir_deg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lightning",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "miles" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Lightning Strikes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_difference(last(\"strike_count\")) FROM \"${lightningSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Storm Distance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "query": "SELECT mean(\"storm_dist\") * 0.6213712 FROM  \"${lightningSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "storm_dist" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sunlight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "alias": "lx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EcoWitt-WS68",
     "select": [
      [
       { "params": [ "light_lux" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "lx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EcoWitt-WS68",
     "select": [
      [
       { "params": [ "lux_raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rainfall",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "in" } },
   "targets": [
    {
     "alias": "Rainfall in Inches",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"rain_mm\")))*0.03937 FROM \"${rainSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Particulate pollution pm02",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "alias": "PM2.5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AQ",
     "select": [
      [
       { "params": [ "pm02" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url::tag",
       "operator": "=",
       "value": "https://api.airgradient.com/public/api/v1/locations/65141/measures/current?token=4cef3c7c-0191-46e6-8aa0-0e3a519f1c24"
      }
     ]
    },
    {
     "alias": "PM10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "pm10" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wet bulb temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Wet Bulb Temp",
     "query": "SELECT last(\"Wet Bulb Temp\") *1.8+32 FROM \"autogen\".\"Wet Bulb Temp\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "Wet Bulb Temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Soil Moisture",
   "type": "timeseries",
   "description": "Soil moisture in the backyard",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Backyard",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Fineoffset-WH51",
     "select": [
      [
       { "params": [ "moisture" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=", "value": "0d7327" }
     ]
    },
    {
     "alias": "Garage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Fineoffset-WH51",
     "select": [
      [
       { "params": [ "moisture" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=", "value": "0d6f50" }
     ]
    },
    {
     "alias": "Dining room",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Fineoffset-WH51",
     "select": [
      [
       { "params": [ "moisture" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=", "value": "0d662d" }
     ]
    }
   ]
  },
  { "title": "Radiation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Radiation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "radusvh" } },
   "yaxes": [
    { "format": "radusvh" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"CPM\")*0.00668  FROM \"cpm\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Other weather stations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "Acurite 606TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"temperature_C\")  *1.8+32 FROM \"Acurite-606TX\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Acurite Tower",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"temperature_C\") *1.8+32 FROM \"Acurite-Tower\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Acurite 6045M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "query": "SELECT mean(\"temperature_C\") *1.8+32 FROM \"Acurite-6045M\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature_C" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Acurite 5-in-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Acurite-5n1",
     "query": "SELECT mean(\"temperature_C\") *1.8+32 FROM \"Acurite-5n1\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature_C" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "LaCrosse",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LaCrosse-TX141THBv2",
     "query": "\n\nSELECT mean(\"temperature_C\") *1.8+32 FROM \"LaCrosse-TX141THBv2\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Bryant",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Bryant",
     "query": "SELECT mean(\"Outdoor Temp\") FROM \"autogen\".\"Bryant\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "Outdoor Temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Garbage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Old Fashioned Barometer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$baroSensor$/",
     "select": [
      [
       { "params": [ "Barometer" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Sensor Monitors for Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Alert List",
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 120 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acurite 6045M Exception Check",
   "type": "timeseries",
   "description": "Battery Check of Temp Sensor",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "AcuRite 06045 Exception",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acurite 5-in-1 Weatherstation",
   "type": "timeseries",
   "description": "Battery Check of Weatherstation",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "AcuRite 5-in-1 Battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-5n1",
     "select": [
      [
       { "params": [ "battery_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lightning Alerts",
   "type": "graph",
   "description": "Alert panel query for lightning",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 120 },
   "targets": [
    {
     "alias": "Strike Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$lightningSensor$/",
     "query": "SELECT non_negative_difference(mean(\"strike_count\")) FROM /^$lightningSensor$/ WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "strike_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$lightningSensor$/",
     "query": "SELECT non_negative_difference(mean(\"storm_dist\")) FROM /^$lightningSensor$/ WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "storm_dist" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acurite 6045M Battery Check",
   "type": "timeseries",
   "description": "Battery Check of Lightning Sensor",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "ACuRite 06045 Battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "select": [
      [
       { "params": [ "battery_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LaCrosse Battery Check",
   "type": "timeseries",
   "description": "Battery Check of Temp Sensor",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LaCrosse-TX141THBv2",
     "query": "SELECT last(\"battery_ok\") FROM \"LaCrosse-TX141THBv2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "battery_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ecowitt Monitor",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Battery Check",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EcoWitt-WH40",
     "select": [
      [
       { "params": [ "battery_ok" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Check for Backyard Soil monitor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 130 },
   "targets": [
    {
     "alias": "Backyard",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Fineoffset-WH51",
     "select": [
      [
       { "params": [ "battery_ok" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id::tag", "operator": "=", "value": "0d74ff" }
     ]
    }
   ]
  },
  {
   "title": "EcoWitt-WS68 Battery Monitor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 130 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EcoWitt-WS68",
     "select": [
      [
       { "params": [ "battery_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}