{
 "title": "Tatooine Weather",
 "description": "Weather",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "tempSensor",
    "label": "Temp Sensor",
    "query": "Acurite-5n1,Acurite-6045M,LaCrosse-TX141THBv2,Acurite-Tower,Hideki-TS04"
   },
   { "name": "windSensor", "label": "Wind Sensor", "query": "Acurite-5n1" },
   {
    "name": "rainSensor",
    "label": "Rain Sensor",
    "query": "EcoWitt-WH40,Acurite-5n1,Hideki-Rain"
   },
   { "name": "lightningSensor", "label": "Lightning Sensor", "query": "Acurite-6045M" },
   { "name": "baroSensor", "label": "Barometer", "query": "Dracal,SenseHat" }
  ]
 },
 "panels": [
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"temperature_C\")  * 1.8+32 FROM \"${tempSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Acurite-5n1",
     "query": "SELECT mean(\"wind_dir_deg\") FROM \"${windSensor}\" WHERE time < now() + 120s",
     "select": [
      [
       { "params": [ "wind_dir_deg" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Windspeed, MPH",
     "measurement": "Acurite-5n1",
     "query": "SELECT last(\"wind_avg_km_h\") * 0.6213712 FROM \"${windSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "wind_avg_km_h" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "query": "SELECT last(\"humidity\") FROM \"${tempSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "strike_count" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dewpoint II",
   "type": "stat",
   "description": "Fixed dewpoint panel, I broke it pretty bad somehow",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Dewpoint",
     "measurement": "Dewpoint",
     "query": "SELECT last(\"dewpoint\") * 1.8000 + 32.00 FROM \"Dewpoint\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       { "params": [ "* 1.8000 + 32.00" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rainfall",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EcoWitt-WH40",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"rain_mm\")))*0.03937 FROM \"${rainSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "rain_mm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Radiation",
   "type": "gauge",
   "description": "Radiation in µSv/hr",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "radusvh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"CPM\")*0.00668  FROM \"cpm\" WHERE $timeFilter GROUP BY time(1h) fill(none)"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "stat",
   "description": "Barometer, MSLP",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$baroSensor$/",
     "select": [
      [
       { "params": [ "Barometer" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heat Index",
   "type": "stat",
   "description": "Heat Index",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Heatindex",
     "select": [
      [
       { "params": [ "heatindex" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1.8+32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "🗲 Strikes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "🗲" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"strike_count\"))) FROM \"${lightningSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "strike_count" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Baro",
   "type": "stat",
   "description": "difference between readings for calculating \"rising\" and \"falling\" without looking at a graph.\n\nOfficial UK met standards are what I used because they were the first I found.",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$baroSensor$/",
     "query": "SELECT last(\"Barometer\") FROM /^$baroSensor$/ WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Barometer" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "TEMPS/HUMIDITY",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "humidity", "label": "Humidity" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LaCrosse-TX141THBv2",
     "query": "SELECT last(\"temperature_C\")  *1.8+32 FROM \"${tempSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature_C" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *1.8+32" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LaCrosse-TX141THBv2",
     "query": "SELECT last(\"humidity\") FROM \"${tempSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Dewpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Dewpoint",
     "query": "SELECT last(\"dewpoint\")  *1.8+32 FROM \"Dewpoint\"  WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Heat Index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Heatindex",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "heatindex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1.8+32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "mph" }
   ],
   "targets": [
    {
     "alias": "mph",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "${weatherStation}",
     "query": "SELECT last(\"wind_avg_km_h\") * 0.6213712 FROM \"${windSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "wind_avg_km_h" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 0.6213712" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "graph",
   "description": "Barometric Pressure, normalized for sealevel",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "yaxes": [
    { "format": "pressurehg" }
   ],
   "targets": [
    {
     "alias": "inHg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$baroSensor$/",
     "select": [
      [
       { "params": [ "Barometer" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Wind Direction " }
   ],
   "targets": [
    {
     "alias": "Degrees",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$windSensor$/",
     "query": "SELECT mode(\"wind_dir_deg\") FROM /^$windSensor$/ WHERE $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "wind_dir_deg" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lightning",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "miles" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Lightning Strikes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_difference(last(\"strike_count\")) FROM \"${lightningSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Storm Distance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "query": "SELECT mean(\"storm_dist\") * 0.6213712 FROM  \"${lightningSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "storm_dist" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rainfall",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "in" }
   ],
   "targets": [
    {
     "alias": "Rainfall in Inches",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"rain_mm\")))*0.03937 FROM \"${rainSensor}\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Radiation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Radiation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "radusvh" } },
   "yaxes": [
    { "format": "radusvh" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"CPM\")*0.00668  FROM \"cpm\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Other weather stations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Acurite 606TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"temperature_C\")  *1.8+32 FROM \"Acurite-606TX\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Hideki TS04",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"temperature_C\")  *1.8+32 FROM \"Hideki-TS04\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Acurite Tower",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"temperature_C\") *1.8+32 FROM \"Acurite-Tower\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Acurite 6045M",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "query": "SELECT mean(\"temperature_C\") *1.8+32 FROM \"Acurite-6045M\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature_C" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Acurite 5-in-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Acurite-5n1",
     "query": "SELECT last(\"temperature_C\") *1.8+32 FROM \"Acurite-5n1\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature_C" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "LaCrosse",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LaCrosse-TX141THBv2",
     "query": "\n\nSELECT last(\"temperature_C\") *1.8+32 FROM \"LaCrosse-TX141THBv2\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Garbage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Old Fashioned Barometer",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$baroSensor$/",
       "select": [
        [
         { "params": [ "Barometer" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Old Fashioned Barometer II",
     "type": "briangann-gauge-panel",
     "gridPos": { "h": 9, "w": 7, "x": 12, "y": 15 },
     "format": "pressurehg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$baroSensor$/",
       "select": [
        [
         { "params": [ "Barometer" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Sensor Monitors for Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Alert List",
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 69 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acurite 6045M Exception Check",
   "type": "graph",
   "description": "Battery Check of Temp Sensor",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 69 },
   "targets": [
    {
     "alias": "AcuRite 06045 Exception",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acurite 5-in-1 Weatherstation",
   "type": "graph",
   "description": "Battery Check of Weatherstation",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 69 },
   "targets": [
    {
     "alias": "AcuRite 5-in-1 Battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-5n1",
     "select": [
      [
       { "params": [ "battery_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lightning Alerts",
   "type": "graph",
   "description": "Alert panel query for lightning",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 69 },
   "targets": [
    {
     "alias": "Strike Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$lightningSensor$/",
     "query": "SELECT non_negative_difference(mean(\"strike_count\")) FROM /^$lightningSensor$/ WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "strike_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$lightningSensor$/",
     "query": "SELECT non_negative_difference(mean(\"storm_dist\")) FROM /^$lightningSensor$/ WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "storm_dist" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Acurite 6045M Battery Check",
   "type": "graph",
   "description": "Battery Check of Lightning Sensor",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 74 },
   "targets": [
    {
     "alias": "ACuRite 06045 Battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Acurite-6045M",
     "select": [
      [
       { "params": [ "battery_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LaCrosse Battery Check",
   "type": "graph",
   "description": "Battery Check of Temp Sensor",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LaCrosse-TX141THBv2",
     "query": "SELECT last(\"battery_ok\") FROM \"LaCrosse-TX141THBv2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "battery_ok" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ecowitt Monitor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 74 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EcoWitt-WH40",
     "select": [
      [
       { "params": [ "protocol" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}